r"""
check_consistency.py -- fails the build if the manuscript, supplement or
cover letter has a hard-coded digit adjacent to "seed", "dB", or "rad/"
outside a macro invocation. Every such quantity must come from a
\NumbersTexMacro (numbers.tex, generated by make_numbers_tex.py from the
result files), never typed directly, so that no number can contradict
another.

Method: strip LaTeX comments and macro invocations (\Foo or \Foo{...} --
these are fine, they're exactly how numbers should appear) from the text,
then regex-search what's left for a hard-coded number next to one of the
three trigger words. This intentionally does NOT touch numbers.tex itself
(that file's whole job is to contain literal numbers).

Usage: python scripts/check_consistency.py [file.tex ...]
       (default: paper/manuscript.tex, supplement.tex, cover_letter.tex)
Exit code 0 = clean, 1 = violations found (build should fail).
"""
import os
import re
import sys

TRIGGER_WORDS = ["seed", "seeds", "dB", "rad/"]

MACRO_INVOCATION_RE = re.compile(r"\\[A-Za-z]+(\{[^{}]*\})?")
COMMENT_RE = re.compile(r"(?<!\\)%.*$", re.MULTILINE)
SPACING_RE = re.compile(r"\\[,;:! ]|~")

NUMBER_NEAR_TRIGGER_RE = re.compile(
    r"(\d+(?:\.\d+)?)\s{0,3}(" + "|".join(re.escape(w) for w in TRIGGER_WORDS) + r")"
    r"|(" + "|".join(re.escape(w) for w in TRIGGER_WORDS) + r")\s{0,3}[-=:]?\s{0,3}(\d+(?:\.\d+)?)",
    re.IGNORECASE,
)


def strip_comments_and_macros(text: str) -> str:
    text = COMMENT_RE.sub("", text)
    text = SPACING_RE.sub(" ", text)
    text = MACRO_INVOCATION_RE.sub(" ", text)
    return text


def find_violations(text: str) -> list[tuple]:
    """Returns [(line_no, matched_text), ...] for every hard-coded-number-
    near-trigger-word match found OUTSIDE macro invocations."""
    stripped = strip_comments_and_macros(text)
    violations = []
    for i, line in enumerate(stripped.splitlines(), start=1):
        for m in NUMBER_NEAR_TRIGGER_RE.finditer(line):
            violations.append((i, m.group(0).strip()))
    return violations


def main():
    paper = os.path.join(os.path.dirname(__file__), "..", "..", "paper")
    paths = sys.argv[1:] or [os.path.join(paper, f)
                             for f in ("manuscript.tex", "supplement.tex", "cover_letter.tex")]
    failed = False
    for path in paths:
        with open(path, encoding="utf-8") as f:
            violations = find_violations(f.read())
        name = os.path.basename(path)
        if violations:
            failed = True
            print(f"[check_consistency] FAILED: {len(violations)} hard-coded number(s) "
                  f"adjacent to seed/dB/rad\\/ outside macro invocations in {name}:")
            for line_no, snippet in violations:
                print(f"  line {line_no}: {snippet!r}")
        else:
            print(f"[check_consistency] OK: {name}")
    if failed:
        print("Use a numbers.tex macro (scripts/make_numbers_tex.py) for results, or "
              r"\param{...} for a stated design parameter.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
