"""
Generate paper/manuscript_lengthcheck.tex from paper/manuscript.tex.

JOSA A bills overlength charges against published pages (limit 10). The
length check compiles the SAME body in Optica's two-column journal class
(opticajnl, 9pt), which approximates the composed layout. It is derived
mechanically from the manuscript so it cannot drift from it.

Usage (from part2/code):
    python scripts/make_lengthcheck.py
    cd ../paper && pdflatex manuscript_lengthcheck && bibtex manuscript_lengthcheck \
        && pdflatex manuscript_lengthcheck && pdflatex manuscript_lengthcheck
"""
import os
import re

PAPER = os.path.join(os.path.dirname(__file__), "..", "..", "paper")
SRC = os.path.join(PAPER, "manuscript.tex")
OUT = os.path.join(PAPER, "manuscript_lengthcheck.tex")

PREAMBLE = r"""%% AUTO-GENERATED by part2/code/scripts/make_lengthcheck.py from manuscript.tex.
%% Do not edit; regenerate. Two-column journal layout, for page counting only.
\documentclass[9pt,twocolumn,twoside]{opticajnl}
\journal{opticajournal}
\setboolean{shortarticle}{false}
\usepackage{tabularx}
\usepackage{amsmath}
\input{numbers}

\begin{document}

\title{%(title)s}

\author[1,*]{Chaitanya Tripathi}
\affil[1]{%(affil)s}
\affil[*]{%(email)s}

"""


def _arg(src, cmd):
    """Contents of the first {...} argument of \\cmd, with nested braces."""
    i = src.index("\\" + cmd + "{") + len(cmd) + 2
    depth, j = 1, i
    while depth:
        depth += {"{": 1, "}": -1}.get(src[j], 0)
        j += 1
    return src[i:j - 1]


def main():
    src = open(SRC, encoding="utf-8").read()
    title = _arg(src, "title")
    affil = re.sub(r"\\authormark\{[^}]*\}", "", _arg(src, "address"))
    email = re.sub(r"\\authormark\{[^}]*\}", "", _arg(src, "email"))
    abstract = re.search(r"\\begin\{abstract\*\}(.*?)\\end\{abstract\*\}", src, re.S).group(1)
    body = src.split(r"\end{abstract*}", 1)[1].split(r"\end{document}", 1)[0]
    body = body.replace(r"\begin{figure}", r"\begin{figure*}").replace(r"\end{figure}", r"\end{figure*}")
    body = body.replace(r"\begin{figure*}[!htbp]", r"\begin{figure*}[!t]")
    head = PREAMBLE.replace("%(title)s", title).replace("%(affil)s", affil).replace("%(email)s", email)
    out = head + "\\begin{abstract}" + abstract + "\\end{abstract}\n\n\\maketitle\n" + body + "\\end{document}\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
