"""
Generate paper/oe_main_lengthcheck.tex from paper/oe_main.tex.

The length check compiles the SAME body in Optica's two-column journal class
(opticajnl, 9pt), which approximates the composed page count Applied Optics
bills against. It used to be a hand-maintained copy and drifted from the
manuscript; this derives it mechanically so it cannot.

Usage: python scripts/make_lengthcheck.py && (cd ../paper && pdflatex oe_main_lengthcheck)
"""
import os
import re

PAPER = os.path.join(os.path.dirname(__file__), "..", "..", "paper")
SRC = os.path.join(PAPER, "oe_main.tex")
OUT = os.path.join(PAPER, "oe_main_lengthcheck.tex")

PREAMBLE = r"""% AUTO-GENERATED by part2/code/scripts/make_lengthcheck.py from oe_main.tex.
% Do not edit; regenerate. Two-column journal layout for page counting only.
\documentclass[9pt,twocolumn,twoside]{opticajnl}
\journal{opticajournal}
\setboolean{shortarticle}{false}
\usepackage{tabularx}
\usepackage{amsmath}
\input{numbers}

\begin{document}

\title{Media-in-the-Loop Holography: Computer-Generated Holography
Through a Differentiable Model of Volume Photopolymer Recording}

\author[1,*]{Chaitanya Tripathi}
\affil[1]{Ashoka University, Sonipat, India}
\affil[*]{chaitanya.tripathi\_ug2025@ashoka.edu.in}

"""


def main():
    src = open(SRC, encoding="utf-8").read()
    abstract = re.search(r"\\begin\{abstract\*\}(.*?)\\end\{abstract\*\}", src, re.S).group(1)
    body = src.split(r"\end{abstract*}", 1)[1]
    body = body.split(r"\end{document}", 1)[0]
    out = (PREAMBLE + "\\begin{abstract}" + abstract + "\\end{abstract}\n\n\\maketitle\n"
           + body + "\\end{document}\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
