r"""
Phase 7.1: generate paper/numbers.tex -- LaTeX macros from
results/summary/paper_numbers.json (analysis/aggregate.py's output). The
manuscript (paper/oe_main.tex) uses ONLY these macros for any quantitative
claim; this is the structural fix for transcription errors (the K=7.85dB
oracle-vs-K=7.85rad/um coincidence resolved in docs/provenance_report.md)
and for internal contradictions (an old draft's abstract claiming "2
seeds" while its own Sec. 5 retracts it -- with a \SeedCount macro
sourced from one place, that class of bug becomes unbuildable).

Every macro is emitted, even when the underlying data doesn't exist yet:
missing data emits \newcommand{\Foo}{[PENDING]} (visibly flagged in the
compiled PDF, red-colored if xcolor is loaded) rather than being silently
omitted (which would just produce an "undefined control sequence" LaTeX
error with no indication of WHY) or fabricated (ground rule 1). This
means oe_main.tex can be built at any point in the project and will
render, honestly showing exactly what's pending.

Usage: python scripts/make_numbers_tex.py
"""
import json
import os
import statistics
import sys

HERE = os.path.dirname(__file__)
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, ROOT)

PAPER_NUMBERS_PATH = os.path.join(ROOT, "results", "summary", "paper_numbers.json")
OUT_PATH = os.path.join(ROOT, "..", "paper", "numbers.tex")

BUDGET_LABELS = {2.0: "TwoX", 4.0: "FourX", 8.0: "EightX"}
PENDING = r"\textcolor{red}{[PENDING]}"


def fmt(value, spec=".2f"):
    if value is None:
        return None
    return format(value, spec)


def macro(name: str, value) -> str:
    body = PENDING if value is None else value
    return f"\\newcommand{{\\{name}}}{{{body}}}\n"


def build_macros(paper_numbers: dict) -> str:
    lines = ["% AUTO-GENERATED by scripts/make_numbers_tex.py -- DO NOT HAND-EDIT.\n",
            "% Regenerate: python scripts/make_numbers_tex.py\n",
            "\\usepackage{xcolor}  % for the [PENDING] flag color, harmless if already loaded\n",
            "\n"]

    closure = paper_numbers.get("m1_headroom_closure", [])
    seed_counts = set()
    for row in closure:
        label = BUDGET_LABELS.get(row.get("budget"))
        if label is None:
            continue
        if row.get("status") == "no_data":
            lines.append(macro(f"MeasuredContrast{label}", None))
            lines.append(macro(f"KcPred{label}", None))
            lines.append(macro(f"Kstar{label}Interp", None))
            lines.append(macro(f"Kstar{label}CI", None))
            lines.append(macro(f"MeanGain{label}", None))
            continue
        lines.append(macro(f"MeasuredContrast{label}", fmt(row.get("measured_contrast_C"))))
        lines.append(macro(f"KcPred{label}", fmt(row.get("predicted_Kc_from_measured_C"))))
        lines.append(macro(f"Kstar{label}Interp", fmt(row.get("observed_Kstar_interp"))))
        lines.append(macro(f"Kstar{label}CI", fmt(row.get("observed_Kstar_ci"))))
        curve = row.get("gain_curve", [])
        mean_gain = statistics.fmean(g for _, g, _, _ in curve) if curve else None
        lines.append(macro(f"MeanGain{label}", fmt(mean_gain)))
        min_gain = min((g for _, g, _, _ in curve), default=None)
        lines.append(macro(f"MinGain{label}", fmt(min_gain)))

    # Worst-case (minimum) gain across ALL budgets/K -- supports the "gain
    # never goes negative anywhere" claim with one concrete number, since
    # the per-budget MinGain{label} macros above already cover each budget
    # individually.
    if closure:
        eightx = next((r for r in closure if r.get("budget") == 8.0), None)
        if eightx and eightx.get("gain_curve"):
            curve = eightx["gain_curve"]
            lines.append(macro("MinGainAllBudgets",
                               fmt(min(g for r in closure if r.get("gain_curve")
                                      for _, g, _, _ in r["gain_curve"]))))

    # S1: physics-component ablation. Ratio of each ablation's K-averaged
    # gain to the baseline condition's -- >1 means removing that term
    # INCREASED gain (the term was suppressing MIL's advantage over BSGD
    # in the intact model), ~1 means the term isn't doing much for this
    # comparison.
    s1 = paper_numbers.get("s1_ablation_summary", {})
    if s1.get("status") == "ok":
        by_cond = s1.get("by_condition", {})
        ratios = s1.get("ratio_to_baseline", {})
        lines.append(macro("SOneBaselineGain", fmt(by_cond.get("baseline", {}).get("mean"))))
        lines.append(macro("SOneNoSaturationGain",
                           fmt(by_cond.get("no_saturation_approx", {}).get("mean"))))
        lines.append(macro("SOneNoSaturationRatio", fmt(ratios.get("no_saturation_approx"), ".1f")))
        lines.append(macro("SOneNoDiffusionRatio", fmt(ratios.get("no_diffusion"), ".2f")))
        lines.append(macro("SOneNoNonlocalityRatio", fmt(ratios.get("no_nonlocality"), ".2f")))
        lines.append(macro("SOneNoDyeDepletionRatio", fmt(ratios.get("no_dye_depletion"), ".2f")))
    else:
        for name in ("SOneBaselineGain", "SOneNoSaturationGain", "SOneNoSaturationRatio",
                    "SOneNoDiffusionRatio", "SOneNoNonlocalityRatio", "SOneNoDyeDepletionRatio"):
            lines.append(macro(name, None))

    # S2: NPDD parameter sensitivity. Overall min/max K-averaged gain
    # across all tested +/-50% D0/sigma/kappa perturbations, vs. the
    # unperturbed baseline -- supports "the result is not sensitive to
    # getting these parameters individually wrong."
    s2 = paper_numbers.get("s2_sensitivity_summary", {})
    if s2.get("status") == "ok":
        lines.append(macro("STwoBaselineGain", fmt(s2.get("baseline", {}).get("mean"))))
        lines.append(macro("STwoGainMin", fmt(s2.get("overall_min"))))
        lines.append(macro("STwoGainMax", fmt(s2.get("overall_max"))))
    else:
        for name in ("STwoBaselineGain", "STwoGainMin", "STwoGainMax"):
            lines.append(macro(name, None))

    # S3: twin-MISCALIBRATION robustness. These are the macros the paper's
    # robustness sentence is written against -- NOT S2's, which cannot
    # support such a sentence (S2 keeps the perturbation common to both
    # arms, where the paired design makes it cancel by construction).
    #
    # SThreeWorstWithinFifty is the number that matters: the lowest
    # K-averaged paired gain over EVERY parameter at every perturbation
    # inside +/-50%. If it is positive, the claim holds over the whole
    # stated range. SThreeDnMaxFlipPct records where the one parameter
    # that does eventually fail crosses zero, so the paper states a
    # located boundary instead of an unbounded claim.
    s3 = paper_numbers.get("s3_mismatch_summary", {})
    if s3.get("status") == "ok":
        by_param = s3.get("by_param", {})
        lines.append(macro("SThreeNominalGain", fmt(s3.get("nominal", {}).get("mean"))))

        within, outside_worst = [], []
        for param, v in by_param.items():
            for pct_s, stat in v.get("by_pct", {}).items():
                if stat.get("mean") is None:
                    continue
                (within if abs(int(pct_s)) <= 50 else outside_worst).append(
                    (int(pct_s), param, stat["mean"]))
        if within:
            lo = min(within, key=lambda t: t[2])
            hi = max(within, key=lambda t: t[2])
            lines.append(macro("SThreeWorstWithinFifty", fmt(lo[2])))
            lines.append(macro("SThreeWorstWithinFiftyParam", lo[1].replace("_", "\\_")))
            lines.append(macro("SThreeBestWithinFifty", fmt(hi[2])))
        else:
            for n in ("SThreeWorstWithinFifty", "SThreeWorstWithinFiftyParam",
                      "SThreeBestWithinFifty"):
                lines.append(macro(n, None))

        dn = by_param.get("dn_max", {})
        lines.append(macro("SThreeDnMaxFlipPct",
                           str(dn.get("sign_flip_pct")) if dn.get("sign_flip_pct")
                           is not None else None))
        lines.append(macro("SThreeDnMaxWorstGain", fmt(dn.get("worst_mean_gain"))))
        by_pct = dn.get("by_pct", {})
        lines.append(macro("SThreeDnMaxAtHundred", fmt(by_pct.get("100", {}).get("mean"))))
        lines.append(macro("SThreeDnMaxAtMinusSixtyThree",
                           fmt(by_pct.get("-63", {}).get("mean"))))
        # Whether ANY parameter flips sign inside the +/-50% claim range.
        flips_within = [v.get("sign_flip_pct") for v in by_param.values()
                        if v.get("sign_flip_pct") is not None
                        and abs(v["sign_flip_pct"]) <= 50]
        lines.append(macro("SThreeAnyFlipWithinFifty",
                           "yes" if flips_within else "no"))
    else:
        for name in ("SThreeNominalGain", "SThreeWorstWithinFifty",
                     "SThreeWorstWithinFiftyParam", "SThreeBestWithinFifty",
                     "SThreeDnMaxFlipPct", "SThreeDnMaxWorstGain",
                     "SThreeDnMaxAtHundred", "SThreeDnMaxAtMinusSixtyThree",
                     "SThreeAnyFlipWithinFifty"):
            lines.append(macro(name, None))

    # SAT: how much of media-in-the-loop's advantage the cheap
    # saturation-only surrogate recovers, per budget, plus the surrogate's
    # own calibration quality (a SAT number is not interpretable without
    # knowing how well a purely pointwise model could fit the twin at all).
    sat = paper_numbers.get("sat_surrogate_summary", {})
    if sat.get("status") == "ok":
        bb = sat.get("by_budget", {})
        for budget, suffix in (("2.0", "TwoX"), ("4.0", "FourX"), ("8.0", "EightX")):
            v = bb.get(budget, {})
            ok = v.get("status") == "ok"
            lines.append(macro(f"SATMeanGain{suffix}",
                               fmt(v.get("sat_mean_gain")) if ok else None))
            frac = v.get("fraction_of_mil") if ok else None
            lines.append(macro(f"SATFracOfMIL{suffix}",
                               fmt(100.0 * frac, ".0f") if frac is not None else None))
        lines.append(macro("SATFitNRMSE",
                           fmt(sat.get("fit_nrmse", {}).get("mean"), ".3f")))
        lines.append(macro("SATFitAEff",
                           fmt(sat.get("fit_a_eff", {}).get("mean"), ".2f")))
    else:
        for name in ("SATMeanGainTwoX", "SATFracOfMILTwoX", "SATMeanGainFourX",
                     "SATFracOfMILFourX", "SATMeanGainEightX",
                     "SATFracOfMILEightX", "SATFitNRMSE", "SATFitAEff"):
            lines.append(macro(name, None))

    # SAT at the sub-cliff K the M1 grid cannot reach (see
    # sat_surrogate_summary_m2's note in analysis/aggregate.py).
    satm2 = paper_numbers.get("sat_surrogate_summary_m2", {})
    if satm2.get("status") == "ok":
        v = satm2.get("by_budget", {}).get("2.0", {})
        ok = v.get("status") == "ok"
        lines.append(macro("SATSubCliffGain",
                           fmt(v.get("sat_mean_gain")) if ok else None))
        lines.append(macro("SATSubCliffMILGain",
                           fmt(v.get("mil_mean_gain")) if ok else None))
        frac = v.get("fraction_of_mil") if ok else None
        lines.append(macro("SATSubCliffFracOfMIL",
                           fmt(100.0 * frac, ".0f") if frac is not None else None))
        # Per-K structure: the pooled fraction averages away the fact that
        # the surrogate is strong at low K and weak at high K, which is
        # the practically useful part of the result.
        by_K = {}
        for bud, vv in satm2.get("by_budget", {}).items():
            if vv.get("status") != "ok":
                continue
            for K, f in vv.get("fraction_by_K", {}).items():
                by_K.setdefault(K, []).append(f)
        if by_K:
            Ks = sorted(by_K, key=float)
            sub, post = Ks[0], Ks[-1]
            lines.append(macro("SATSubCliffFracMin",
                               fmt(100.0 * min(by_K[sub]), ".0f")))
            lines.append(macro("SATSubCliffFracMax",
                               fmt(100.0 * max(by_K[sub]), ".0f")))
            lines.append(macro("SATSubCliffK", fmt(float(sub), ".2f")))
            mid = Ks[len(Ks) // 2]
            lines.append(macro("SATNearCliffK", fmt(float(mid), ".2f")))
            lines.append(macro("SATNearCliffFrac",
                               fmt(100.0 * (sum(by_K[mid]) / len(by_K[mid])), ".0f")))
            lines.append(macro("SATPostCliffK", fmt(float(post), ".2f")))
            lines.append(macro("SATPostCliffFracMin",
                               fmt(100.0 * min(by_K[post]), ".0f")))
            lines.append(macro("SATPostCliffFracMax",
                               fmt(100.0 * max(by_K[post]), ".0f")))
        else:
            for name in ("SATSubCliffFracMin", "SATSubCliffFracMax",
                         "SATSubCliffK", "SATNearCliffK", "SATNearCliffFrac",
                         "SATPostCliffK", "SATPostCliffFracMin",
                         "SATPostCliffFracMax"):
                lines.append(macro(name, None))
    else:
        for name in ("SATSubCliffGain", "SATSubCliffMILGain",
                     "SATSubCliffFracOfMIL", "SATSubCliffFracMin",
                     "SATSubCliffFracMax", "SATSubCliffK", "SATNearCliffK",
                     "SATNearCliffFrac", "SATPostCliffK",
                     "SATPostCliffFracMin", "SATPostCliffFracMax"):
            lines.append(macro(name, None))

    # Seed count: consistent across all logged M1 ITERATIVE-method rows (the
    # methods MeanGain/gain-curve claims are actually about), or PENDING if
    # absent/inconsistent. GS/LPC are closed-form and deliberately run at a
    # single seed (no optimizer trajectory to vary) -- excluding them from
    # this check is honest, not a fudge: including them would report a
    # spurious inconsistency for something that isn't a data gap, it's a
    # documented design choice (see manifest.py's build_M1_jobs).
    per_config = paper_numbers.get("per_config", {})
    ITERATIVE_METHODS = {"BSGD", "MIL", "SAT", "ORC", "ORU"}
    m1_seed_counts = {v["n_seeds"] for k, methods in per_config.items()
                      if k.startswith("M1/")
                      for m, v in methods.items() if m in ITERATIVE_METHODS}
    #
    # M1 is no longer a balanced design: a seedbump re-ran seeds 3-7 on a
    # minority of configurations, so a single "N seeds" is not a true
    # statement. Rather than pick one number and be wrong about the rest,
    # emit the range (SeedCountDesc renders "3" when uniform and "3--8"
    # when not, so the macro stays correct if the grid is ever balanced
    # again) plus the modal count and how many cells carry extra seeds.
    if m1_seed_counts:
        lo, hi = min(m1_seed_counts), max(m1_seed_counts)
        lines.append(macro("SeedCountMin", str(lo)))
        lines.append(macro("SeedCountMax", str(hi)))
        lines.append(macro("SeedCountDesc",
                           str(lo) if lo == hi else f"{lo}--{hi}"))
        # Modal count = what most cells actually have.
        counts = [v["n_seeds"] for k, methods in per_config.items()
                  if k.startswith("M1/")
                  for m, v in methods.items() if m in ITERATIVE_METHODS]
        modal = max(set(counts), key=counts.count)
        lines.append(macro("SeedCountModal", str(modal)))
        n_extra = len({k for k, methods in per_config.items()
                       if k.startswith("M1/")
                       and any(v["n_seeds"] > modal
                               for m, v in methods.items()
                               if m in ITERATIVE_METHODS)})
        lines.append(macro("SeedCountNExtraConfigs", str(n_extra)))
        # Kept for any remaining call site: the modal value when uniform,
        # PENDING otherwise, so nothing silently asserts uniformity.
        lines.append(macro("SeedCount", str(lo) if lo == hi else None))
    else:
        for name in ("SeedCountMin", "SeedCountMax", "SeedCountDesc",
                     "SeedCountModal", "SeedCountNExtraConfigs", "SeedCount"):
            lines.append(macro(name, None))

    lines.append(macro("NResultFiles", str(paper_numbers.get("n_result_files", 0))))
    return "".join(lines)


def _load(*parts):
    path = os.path.join(ROOT, *parts)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def build_supplement_macros() -> str:
    """Macros for already-real supplementary data (gradient ablation, RCWA
    incl. E7, GPU mesh convergence, GPU wavelength detuning) -- routed
    through numbers.tex too, for the same zero-hand-typed-numbers reason
    Sec. 7.1 applies to the main manuscript, even though this data
    predates Phase 3 and isn't gated on it."""
    lines = ["\n% --- supplement macros (already-real data, not Phase-3-gated) ---\n"]

    ablation = _load("results_ablation_gradients.json")
    lines.append(macro("AblationCheckpointCosSim",
                       fmt(ablation["fidelity"]["checkpoint_cossim"], ".3f") if ablation else None))
    lines.append(macro("AblationSurrogateCosSim",
                       fmt(ablation["fidelity"]["surrogate_cossim"], ".3f") if ablation else None))

    rcwa3 = _load("results_rcwa.json")
    lines.append(macro("RCWAMaxDevThreeCase",
                       fmt(rcwa3.get("max_abs_deviation"), ".3f") if rcwa3 else None))
    # NOTE: macro names must be letters-only -- LaTeX control words stop
    # at the first non-letter character, so a name like "RCWAE7MaxDev"
    # silently splits into the control sequence \RCWAE followed by literal
    # text "7MaxDev" (and collides with any other macro sharing that same
    # \RCWAE prefix). Caught by an actual pdflatex compile ("Missing
    # \begin{document}" / "Missing number, treated as zero" cascading
    # errors with no clear cause) -- this environment cannot catch this
    # class of bug just by reading the .tex output, only by compiling it.
    rcwa_e7 = _load("results_rcwa_e7.json")
    lines.append(macro("RCWAVGridMaxDev",
                       fmt(rcwa_e7.get("max_abs_deviation"), ".3f") if rcwa_e7 else None))
    lines.append(macro("RCWAVGridNCases", str(rcwa_e7["n_cases"]) if rcwa_e7 else None))

    mesh = _load("results", "gpu_reruns", "npdd_mesh_sweep", "results.json")
    if mesh:
        psnrs = [row["psnr"] for row in mesh["mesh_density"].values()]
        lines.append(macro("MeshPSNRSpread", fmt(max(psnrs) - min(psnrs), ".3f")))
    else:
        lines.append(macro("MeshPSNRSpread", None))

    wl = _load("results", "gpu_reruns", "bpm_wavelength_sweep", "results.json")
    lines.append(macro("WavelengthDesignPSNR",
                       fmt(wl["recording"]["psnr_at_design_wavelength"], ".2f") if wl else None))

    return "".join(lines)


def build_validation_macros() -> str:
    """Macros for experiments/fit_literature_curves.py's output
    (results_literature_fit.json) -- Phase 6/Twin Validation. Emits one
    NRMSE/fit_quality macro per fitted source, plus a count, so Section 6
    can cite exact numbers without hand-typing them. Ground rule 4 applies
    here specifically: a poor fit gets its real NRMSE macro'd in, not
    rounded away or omitted."""
    lines = ["\n% --- validation (Phase 6 / Section 6) macros ---\n"]
    fit_data = _load("results_literature_fit.json")
    fits = fit_data.get("fits", []) if fit_data else []

    lines.append(macro("NLiteratureSources", str(len(fits))))

    # One macro pair per fit, keyed by a letters-only slug derived from the
    # source filename (same macro-name constraint noted above for RCWA).
    for fit in fits:
        stem = fit["file"].replace(".csv", "")
        slug = "".join(ch for ch in stem.title().replace("_", "") if ch.isalpha())
        lines.append(macro(f"NRMSE{slug}", fmt(fit["nrmse"], ".2f")))

    if fits:
        worst = max(fits, key=lambda f: f["nrmse"])
        best = min(fits, key=lambda f: f["nrmse"])
        lines.append(macro("NRMSEWorstFit", fmt(worst["nrmse"], ".2f")))
        lines.append(macro("NRMSEBestFit", fmt(best["nrmse"], ".2f")))
        n_good = sum(1 for f in fits if f["fit_quality"] == "GOOD")
        lines.append(macro("NGoodFits", str(n_good)))

        # In-regime-only (K within this paper's own tested M1/S1/S2 grid,
        # 1.96-15.71 rad/um) worst/best -- the Gate-A/A.5 finding that
        # K=24.94 (Hsieh) sits outside that range and must not count as
        # in-regime model-structure evidence. Threshold matches the
        # K_GRID bounds already used elsewhere (see Results section).
        in_regime = [f for f in fits if 1.96 <= f["K"] <= 15.71]
        if in_regime:
            worst_ir = max(in_regime, key=lambda f: f["nrmse"])
            best_ir = min(in_regime, key=lambda f: f["nrmse"])
            lines.append(macro("NRMSEWorstInRegime", fmt(worst_ir["nrmse"], ".2f")))
            lines.append(macro("NRMSEBestInRegime", fmt(best_ir["nrmse"], ".2f")))
            lines.append(macro("NInRegimeSources", str(len(in_regime))))
        else:
            lines.append(macro("NRMSEWorstInRegime", None))
            lines.append(macro("NRMSEBestInRegime", None))
            lines.append(macro("NInRegimeSources", "0"))

        # dn_max disagreement between the two Bayfol series (same paper,
        # same K, two exposure intensities) -- named directly in Section 6
        # rather than smoothed over. Only computed when both exist.
        bayfol = [f for f in fits if "bruder2017" in f.get("file", "")
                 and f.get("second_param") == "dn_max"]
        if len(bayfol) == 2:
            vals = sorted(f["second_param_fit"] for f in bayfol)
            ratio = vals[1] / vals[0] if vals[0] > 0 else None
            lines.append(macro("BayfolDnMaxRatio", fmt(ratio, ".1f") if ratio else None))
        else:
            lines.append(macro("BayfolDnMaxRatio", None))
    else:
        lines.append(macro("NRMSEWorstFit", None))
        lines.append(macro("NRMSEBestFit", None))
        lines.append(macro("NRMSEWorstInRegime", None))
        lines.append(macro("NRMSEBestInRegime", None))
        lines.append(macro("NInRegimeSources", "0"))
        lines.append(macro("BayfolDnMaxRatio", None))
        lines.append(macro("NGoodFits", None))

    return "".join(lines)


def build_shrinkage_bound_macros() -> str:
    """Macros for the Discussion's shrinkage-induced lateral-shift bound
    (D.4 in the work spec: 'named in the intro, never quantified' --
    closed by computing the exact, already-implemented shrinkage/slant
    shift formula in holomedia/diffraction.py at the default medium's
    parameters, not by asserting the effect is negligible without
    checking, and not by inventing a number)."""
    import math
    lines = ["\n% --- shrinkage-induced shift bound (Discussion) macros ---\n"]
    try:
        from holomedia import MediumParams
        p = MediumParams()  # DEFAULT_MEDIUM-equivalent: shrinkage, thickness
        slant_deg = 20.0  # SlabBPM.forward's own default -- see holomedia/diffraction.py
        tan_phi = math.tan(math.radians(slant_deg))
        shift_um = p.shrinkage * tan_phi * p.thickness
        shift_nm = shift_um * 1000.0
        K_LO, K_HI = 1.96, 15.71  # this paper's own tested K grid (Results section)
        # fraction of a grating period = shift / period; period = 2*pi/K, so
        # LOW K -> long period -> SMALL fraction, HIGH K -> short period ->
        # LARGE fraction. (Named frac_lo/frac_hi by which K they're AT, not
        # by which is numerically larger -- checked this isn't swapped.)
        frac_lo = shift_um / (2 * math.pi / K_LO) * 100.0
        frac_hi = shift_um / (2 * math.pi / K_HI) * 100.0
        lines.append(macro("ShrinkagePct", fmt(p.shrinkage * 100, ".1f")))
        lines.append(macro("ShrinkageSlantDeg", fmt(slant_deg, ".0f")))
        lines.append(macro("ShrinkageThicknessUm", fmt(p.thickness, ".0f")))
        lines.append(macro("ShrinkageShiftNm", fmt(shift_nm, ".1f")))
        lines.append(macro("ShrinkageFracLowK", fmt(frac_lo, ".1f")))
        lines.append(macro("ShrinkageFracHighK", fmt(frac_hi, ".1f")))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: shrinkage-bound macros failed ({e}); "
              f"emitting PENDING.")
        for name in ("ShrinkagePct", "ShrinkageSlantDeg", "ShrinkageThicknessUm",
                    "ShrinkageShiftNm", "ShrinkageFracLowK", "ShrinkageFracHighK"):
            lines.append(macro(name, None))
    return "".join(lines)


def build_r1_macros() -> str:
    """ROneSeedValue -- pulled from the actual results file's own recorded
    seed (results_r1_reconstructions.json), not the script constant
    directly, so a future change to make_r1_reconstructions.py's SEED
    can't silently drift from what the caption claims."""
    lines = ["\n% --- R1 reconstruction figure macros ---\n"]
    d = _load("results_r1_reconstructions.json")
    if d and d.get("results"):
        seeds = {r["seed"] for r in d["results"]}
        lines.append(macro("ROneSeedValue", str(seeds.pop()) if len(seeds) == 1 else None))
    else:
        lines.append(macro("ROneSeedValue", None))
    return "".join(lines)


def build_cost_benefit_macros() -> str:
    """ComputeMatchRatio for the D.3 cost-benefit paragraph -- pulled
    directly from experiments/manifest.py's own constant, not retyped."""
    lines = ["\n% --- cost-benefit (Sec. 5.1) macros ---\n"]
    try:
        from manifest import COMPUTE_MATCH_RATIO
        lines.append(macro("ComputeMatchRatio", fmt(COMPUTE_MATCH_RATIO, ".1f")))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: cost-benefit macros failed ({e}); emitting PENDING.")
        lines.append(macro("ComputeMatchRatio", None))
    return "".join(lines)


def build_baseline_completeness_macros() -> str:
    """Macros for Sec. 5.2 (Baseline completeness, F4b): min/max paired
    gain of GS and LPC over media-blind SGD at budget=2x, and MIL's own
    min at the same budget for the contrast. Computed directly via
    analysis.aggregate (not read from a pre-baked paper_numbers.json
    field, unlike build_macros above) -- still fully regenerated from the
    raw per-job result JSONs each run, just one aggregation hop shorter;
    ground rule 1 (no hand-typed numbers in the manuscript) still holds,
    this is the "goes into a script" the rule requires."""
    lines = ["\n% --- baseline completeness (Sec. 5.2 / F4b) macros ---\n"]
    try:
        from analysis.aggregate import (load_all_results, group_by_config,
                                        gain_curve, gain_vs_bsgd_seed_mean)
        grouped = group_by_config(load_all_results())
        for method, macro_prefix in (("GS", "GSGain"), ("LPC", "LPCGain")):
            curve = gain_vs_bsgd_seed_mean(grouped, "M1", 2.0, method=method)
            vals = [v[1] for v in curve]
            lines.append(macro(f"{macro_prefix}Min", fmt(min(vals), ".2f") if vals else None))
            lines.append(macro(f"{macro_prefix}Max", fmt(max(vals), ".2f") if vals else None))
        mil_curve = gain_curve(grouped, "M1", 2.0, method="MIL")
        mil_vals = [v[1] for v in mil_curve]
        lines.append(macro("MILGainMinAtTwoX", fmt(min(mil_vals), ".2f") if mil_vals else None))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: baseline-completeness macros failed ({e}); "
              f"emitting PENDING for all of them.")
        for name in ("GSGainMin", "GSGainMax", "LPCGainMin", "LPCGainMax", "MILGainMinAtTwoX"):
            lines.append(macro(name, None))
    return "".join(lines)


def main():
    paper_numbers = {}
    if os.path.exists(PAPER_NUMBERS_PATH):
        with open(PAPER_NUMBERS_PATH) as f:
            paper_numbers = json.load(f)
    else:
        print(f"[make_numbers_tex] WARNING: {PAPER_NUMBERS_PATH} not found "
              f"-- run analysis/aggregate.py first. Emitting all-PENDING macros.")

    tex = (build_macros(paper_numbers) + build_supplement_macros()
          + build_validation_macros() + build_baseline_completeness_macros()
          + build_shrinkage_bound_macros() + build_cost_benefit_macros()
          + build_r1_macros())
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(tex)
    n_pending = tex.count(PENDING)
    print(f"wrote {OUT_PATH} ({tex.count(chr(10)) } lines, {n_pending} macros still PENDING)")


if __name__ == "__main__":
    main()
