r"""
Generate paper/numbers.tex -- LaTeX macros from
results/summary/paper_numbers.json (analysis/aggregate.py's output) and the
other committed result files. The manuscript, supplement and cover letter
use ONLY these macros for any quantitative claim, so a number can never be
transcribed wrongly or disagree between two places.

Every macro is emitted, even when the underlying data doesn't exist yet:
missing data emits \newcommand{\Foo}{[PENDING]} (visibly flagged in the
compiled PDF) rather than being silently omitted or fabricated, and
scripts/make_submission_package.py refuses to build while any [PENDING]
reaches a PDF.

Usage: python scripts/make_numbers_tex.py
"""
import json
import os
import statistics
import sys

HERE = os.path.dirname(__file__)
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, ROOT)

PAPER_NUMBERS_PATH = os.path.join(ROOT, "results", "summary", "paper_numbers.json")
OUT_PATH = os.path.join(ROOT, "..", "paper", "numbers.tex")

BUDGET_LABELS = {2.0: "TwoX", 4.0: "FourX", 8.0: "EightX"}
PENDING = r"\textcolor{red}{[PENDING]}"


def fmt(value, spec=".2f"):
    if value is None:
        return None
    return format(value, spec)


def fmt_sci(value, digits=1):
    r"""Format a small positive number as LaTeX scientific notation, e.g.
    6.5\times10^{-6}, for use inside math mode."""
    if value is None:
        return None
    mant, exp = f"{value:.{digits}e}".split("e")
    return mant + r"\times10^{" + str(int(exp)) + "}"


def macro(name: str, value) -> str:
    body = PENDING if value is None else value
    return f"\\newcommand{{\\{name}}}{{{body}}}\n"


def build_macros(paper_numbers: dict) -> str:
    lines = ["% AUTO-GENERATED by scripts/make_numbers_tex.py -- DO NOT HAND-EDIT.\n",
            "% Regenerate: python scripts/make_numbers_tex.py\n",
            "\\usepackage{xcolor}  % for the [PENDING] flag color, harmless if already loaded\n",
            "% \\param{...} marks a stated design parameter, as opposed to a result (which\n",
            "% must be one of the macros below); scripts/check_consistency.py accepts it.\n",
            "\\providecommand{\\param}[1]{#1}\n",
            "\n"]

    closure = paper_numbers.get("m1_headroom_closure", [])
    for row in closure:
        label = BUDGET_LABELS.get(row.get("budget"))
        if label is None:
            continue
        if row.get("status") == "no_data":
            lines.append(macro(f"MeasuredContrast{label}", None))
            lines.append(macro(f"KcPred{label}", None))
            lines.append(macro(f"Kstar{label}Interp", None))
            lines.append(macro(f"Kstar{label}CI", None))
            lines.append(macro(f"MeanGain{label}", None))
            continue
        lines.append(macro(f"MeasuredContrast{label}", fmt(row.get("measured_contrast_C"))))
        lines.append(macro(f"KcPred{label}", fmt(row.get("predicted_Kc_from_measured_C"))))
        lines.append(macro(f"Kstar{label}Interp", fmt(row.get("observed_Kstar_interp")) or "none"))
        lines.append(macro(f"Kstar{label}CI", fmt(row.get("observed_Kstar_ci")) or "none"))
        curve = row.get("gain_curve", [])
        mean_gain = statistics.fmean(g for _, g, _, _ in curve) if curve else None
        lines.append(macro(f"MeanGain{label}", fmt(mean_gain)))
        min_gain = min((g for _, g, _, _ in curve), default=None)
        lines.append(macro(f"MinGain{label}", fmt(min_gain)))

    if closure:
        eightx = next((r for r in closure if r.get("budget") == 8.0), None)
        if eightx and eightx.get("gain_curve"):
            curve = eightx["gain_curve"]
            lines.append(macro("MinGainAllBudgets",
                               fmt(min(g for r in closure if r.get("gain_curve")
                                      for _, g, _, _ in r["gain_curve"]))))

    _SLANT = {0.0: "Zero", 2.5: "TwoFive", 5.0: "Five", 7.5: "SevenFive",
              10.0: "Ten", 15.0: "Fifteen", 20.0: "Twenty"}
    _KLAB = {1.9635: "KLow", 3.927: "KMid"}
    s8 = paper_numbers.get("s8_slant_summary", {})
    for K, klab in _KLAB.items():
        for sl, slab in _SLANT.items():
            stat = (s8.get("by_K", {}).get(str(K), {}).get(str(sl), {}) if s8.get("status") == "ok" else {})
            lines.append(macro(f"SEightGain{klab}Slant{slab}", fmt(stat.get("mean"), ".3f")))
            lines.append(macro(f"SEightLo{klab}Slant{slab}", fmt(stat.get("ci95_lo"), ".3f")))
            lines.append(macro(f"SEightHi{klab}Slant{slab}", fmt(stat.get("ci95_hi"), ".3f")))

    _NZ = {32: "ThirtyTwo", 128: "OneTwentyEight", 256: "TwoFiftySix"}
    nz0 = paper_numbers.get("nz0_convergence_summary", {})
    for nz, nlab in _NZ.items():
        stat = (nz0.get("pooled", {}).get(str(nz), {}) if nz0.get("status") == "ok" else {})
        lines.append(macro(f"NZZeroPooledGain{nlab}", fmt(stat.get("mean"), ".3f")))
        lines.append(macro(f"NZZeroPooledLo{nlab}", fmt(stat.get("ci95_lo"), ".3f")))
        lines.append(macro(f"NZZeroPooledHi{nlab}", fmt(stat.get("ci95_hi"), ".3f")))
    for K, klab in _KLAB.items():
        for nz, nlab in _NZ.items():
            stat = (nz0.get("by_K", {}).get(str(K), {}).get(str(nz), {}) if nz0.get("status") == "ok" else {})
            lines.append(macro(f"NZZeroGain{klab}{nlab}", fmt(stat.get("mean"), ".3f")))

    s1 = paper_numbers.get("s1_ablation_summary", {})
    if s1.get("status") == "ok":
        by_cond = s1.get("by_condition", {})
        ratios = s1.get("ratio_to_baseline", {})
        lines.append(macro("SOneBaselineGain", fmt(by_cond.get("baseline", {}).get("mean"))))
        lines.append(macro("SOneNoSaturationGain",
                           fmt(by_cond.get("no_saturation", {}).get("mean"))))
        lines.append(macro("SOneNoSaturationRatio", fmt(ratios.get("no_saturation"), ".1f")))
        lines.append(macro("SOneNoDiffusionRatio", fmt(ratios.get("no_diffusion"), ".2f")))
        lines.append(macro("SOneNoNonlocalityRatio", fmt(ratios.get("no_nonlocality"), ".2f")))
        lines.append(macro("SOneNoDyeDepletionRatio", fmt(ratios.get("no_dye_depletion"), ".2f")))
    else:
        for name in ("SOneBaselineGain", "SOneNoSaturationGain", "SOneNoSaturationRatio",
                    "SOneNoDiffusionRatio", "SOneNoNonlocalityRatio", "SOneNoDyeDepletionRatio"):
            lines.append(macro(name, None))

    s2 = paper_numbers.get("s2_sensitivity_summary", {})
    if s2.get("status") == "ok":
        lines.append(macro("STwoBaselineGain", fmt(s2.get("baseline", {}).get("mean"))))
        lines.append(macro("STwoGainMin", fmt(s2.get("overall_min"))))
        lines.append(macro("STwoGainMax", fmt(s2.get("overall_max"))))
    else:
        for name in ("STwoBaselineGain", "STwoGainMin", "STwoGainMax"):
            lines.append(macro(name, None))

    s3 = paper_numbers.get("s3_mismatch_summary", {})
    if s3.get("status") == "ok":
        by_param = s3.get("by_param", {})
        lines.append(macro("SThreeNominalGain", fmt(s3.get("nominal", {}).get("mean"))))

        within, outside_worst = [], []
        for param, v in by_param.items():
            for pct_s, stat in v.get("by_pct", {}).items():
                if stat.get("mean") is None:
                    continue
                (within if abs(int(pct_s)) <= 50 else outside_worst).append(
                    (int(pct_s), param, stat["mean"]))
        if within:
            lo = min(within, key=lambda t: t[2])
            hi = max(within, key=lambda t: t[2])
            lines.append(macro("SThreeWorstWithinFifty", fmt(lo[2])))
            lines.append(macro("SThreeWorstWithinFiftyParam", lo[1].replace("_", "\\_")))
            lines.append(macro("SThreeBestWithinFifty", fmt(hi[2])))
        else:
            for n in ("SThreeWorstWithinFifty", "SThreeWorstWithinFiftyParam",
                      "SThreeBestWithinFifty"):
                lines.append(macro(n, None))

        dn = by_param.get("dn_max", {})
        lines.append(macro("SThreeDnMaxFlipPct",
                           str(dn.get("sign_flip_pct")) if dn.get("sign_flip_pct")
                           is not None else None))
        lines.append(macro("SThreeDnMaxWorstGain", fmt(dn.get("worst_mean_gain"))))
        by_pct = dn.get("by_pct", {})
        lines.append(macro("SThreeDnMaxAtHundred", fmt(by_pct.get("100", {}).get("mean"))))
        most_negative_pct = min((int(p) for p in by_pct if int(p) < 0), default=None)
        lines.append(macro("SThreeDnMaxMostNegativePct",
                           str(most_negative_pct) if most_negative_pct is not None else None))
        lines.append(macro("SThreeDnMaxAtMostNegative",
                           fmt(by_pct.get(str(most_negative_pct), {}).get("mean"))
                           if most_negative_pct is not None else None))
        most_positive_pct = max((int(p) for p in by_pct if int(p) > 0), default=None)
        lines.append(macro("SThreeDnMaxMostPositivePct",
                           str(most_positive_pct) if most_positive_pct is not None else None))
        lines.append(macro("SThreeDnMaxAtMostPositive",
                           fmt(by_pct.get(str(most_positive_pct), {}).get("mean"))
                           if most_positive_pct is not None else None))
        flips_within = [v.get("sign_flip_pct") for v in by_param.values()
                        if v.get("sign_flip_pct") is not None
                        and abs(v["sign_flip_pct"]) <= 50]
        lines.append(macro("SThreeAnyFlipWithinFifty",
                           "yes" if flips_within else "no"))
    else:
        for name in ("SThreeNominalGain", "SThreeWorstWithinFifty",
                     "SThreeWorstWithinFiftyParam", "SThreeBestWithinFifty",
                     "SThreeDnMaxFlipPct", "SThreeDnMaxWorstGain",
                     "SThreeDnMaxAtHundred", "SThreeDnMaxMostNegativePct",
                     "SThreeDnMaxAtMostNegative", "SThreeDnMaxMostPositivePct",
                     "SThreeDnMaxAtMostPositive", "SThreeAnyFlipWithinFifty"):
            lines.append(macro(name, None))

    sat = paper_numbers.get("sat_surrogate_summary", {})
    if sat.get("status") == "ok":
        bb = sat.get("by_budget", {})
        for budget, suffix in (("2.0", "TwoX"), ("4.0", "FourX"), ("8.0", "EightX")):
            v = bb.get(budget, {})
            ok = v.get("status") == "ok"
            lines.append(macro(f"SATMeanGain{suffix}",
                               fmt(v.get("sat_mean_gain")) if ok else None))
            frac = v.get("fraction_of_mil") if ok else None
            lines.append(macro(f"SATFracOfMIL{suffix}",
                               fmt(100.0 * frac, ".0f") if frac is not None else None))
        lines.append(macro("SATFitNRMSE",
                           fmt(sat.get("fit_nrmse", {}).get("mean"), ".3f")))
        lines.append(macro("SATFitAEff",
                           fmt(sat.get("fit_a_eff", {}).get("mean"), ".2f")))
    else:
        for name in ("SATMeanGainTwoX", "SATFracOfMILTwoX", "SATMeanGainFourX",
                     "SATFracOfMILFourX", "SATMeanGainEightX",
                     "SATFracOfMILEightX", "SATFitNRMSE", "SATFitAEff"):
            lines.append(macro(name, None))

    satm2 = paper_numbers.get("sat_surrogate_summary_m2", {})
    if satm2.get("status") == "ok":
        v = satm2.get("by_budget", {}).get("2.0", {})
        ok = v.get("status") == "ok"
        lines.append(macro("SATSubCliffGain",
                           fmt(v.get("sat_mean_gain")) if ok else None))
        lines.append(macro("SATSubCliffMILGain",
                           fmt(v.get("mil_mean_gain")) if ok else None))
        frac = v.get("fraction_of_mil") if ok else None
        lines.append(macro("SATSubCliffFracOfMIL",
                           fmt(100.0 * frac, ".0f") if frac is not None else None))
        by_K = {}
        for bud, vv in satm2.get("by_budget", {}).items():
            if vv.get("status") != "ok":
                continue
            for K, f in vv.get("fraction_by_K", {}).items():
                by_K.setdefault(K, []).append(f)
        if by_K:
            Ks = sorted(by_K, key=float)
            sub, post = Ks[0], Ks[-1]
            lines.append(macro("SATSubCliffFracMin",
                               fmt(100.0 * min(by_K[sub]), ".0f")))
            lines.append(macro("SATSubCliffFracMax",
                               fmt(100.0 * max(by_K[sub]), ".0f")))
            lines.append(macro("SATSubCliffK", fmt(float(sub), ".2f")))
            mid = Ks[len(Ks) // 2]
            lines.append(macro("SATNearCliffK", fmt(float(mid), ".2f")))
            lines.append(macro("SATNearCliffFrac",
                               fmt(100.0 * (sum(by_K[mid]) / len(by_K[mid])), ".0f")))
            lines.append(macro("SATPostCliffK", fmt(float(post), ".2f")))
            lines.append(macro("SATPostCliffFracMin",
                               fmt(100.0 * min(by_K[post]), ".0f")))
            lines.append(macro("SATPostCliffFracMax",
                               fmt(100.0 * max(by_K[post]), ".0f")))
        else:
            for name in ("SATSubCliffFracMin", "SATSubCliffFracMax",
                         "SATSubCliffK", "SATNearCliffK", "SATNearCliffFrac",
                         "SATPostCliffK", "SATPostCliffFracMin",
                         "SATPostCliffFracMax"):
                lines.append(macro(name, None))
    else:
        for name in ("SATSubCliffGain", "SATSubCliffMILGain",
                     "SATSubCliffFracOfMIL", "SATSubCliffFracMin",
                     "SATSubCliffFracMax", "SATSubCliffK", "SATNearCliffK",
                     "SATNearCliffFrac", "SATPostCliffK",
                     "SATPostCliffFracMin", "SATPostCliffFracMax"):
            lines.append(macro(name, None))

    per_config = paper_numbers.get("per_config", {})
    ITERATIVE_METHODS = {"BSGD", "MIL", "SAT", "ORC"}
    m1_seed_counts = {v["n_seeds"] for k, methods in per_config.items()
                      if k.startswith("M1/")
                      for m, v in methods.items() if m in ITERATIVE_METHODS}
    if m1_seed_counts:
        lo, hi = min(m1_seed_counts), max(m1_seed_counts)
        lines.append(macro("SeedCountMin", str(lo)))
        lines.append(macro("SeedCountMax", str(hi)))
        lines.append(macro("SeedCountDesc",
                           str(lo) if lo == hi else f"{lo}--{hi}"))
        counts = [v["n_seeds"] for k, methods in per_config.items()
                  if k.startswith("M1/")
                  for m, v in methods.items() if m in ITERATIVE_METHODS]
        modal = max(set(counts), key=counts.count)
        lines.append(macro("SeedCountModal", str(modal)))
        n_extra = len({k for k, methods in per_config.items()
                       if k.startswith("M1/")
                       and any(v["n_seeds"] > modal
                               for m, v in methods.items()
                               if m in ITERATIVE_METHODS)})
        lines.append(macro("SeedCountNExtraConfigs", str(n_extra)))
        lines.append(macro("SeedCount", str(lo) if lo == hi else None))
    else:
        for name in ("SeedCountMin", "SeedCountMax", "SeedCountDesc",
                     "SeedCountModal", "SeedCountNExtraConfigs", "SeedCount"):
            lines.append(macro(name, None))

    lines.append(macro("NResultFiles", str(paper_numbers.get("n_result_files", 0))))
    return "".join(lines)


def _load(*parts):
    path = os.path.join(ROOT, *parts)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def build_supplement_macros() -> str:
    """Macros for the supplement's numerical checks: the finite-difference
    gradient check (experiments/gradient_check.py) and the Kogelnik-vs-RCWA
    comparison (experiments/rcwa_crosscheck.py)."""
    lines = ["\n% --- supplement macros: gradient check, RCWA ---\n"]

    grad = _load("results_gradient_check.json")
    lines.append(macro("GradCheckMaxRelErr",
                       fmt_sci(grad["max_rel_error"]) if grad else None))
    lines.append(macro("GradCheckNDirs", str(len(grad["directions"])) if grad else None))

    rcwa3 = _load("results_rcwa.json")
    lines.append(macro("RCWAMaxDevThreeCase",
                       fmt(rcwa3.get("max_abs_deviation"), ".3f") if rcwa3 else None))
    rcwa_e7 = _load("results_rcwa_e7.json")
    lines.append(macro("RCWAVGridMaxDev",
                       fmt(rcwa_e7.get("max_abs_deviation"), ".2f") if rcwa_e7 else None))
    lines.append(macro("RCWAVGridNCases", str(rcwa_e7["n_cases"]) if rcwa_e7 else None))
    if rcwa_e7:
        from collections import defaultdict
        import statistics as _stats
        by_geom = defaultdict(list)
        for c in rcwa_e7["cases"]:
            by_geom[c["geometry"]].append(c["abs_deviation"])
        unslanted_max = max((max(v) for k, v in by_geom.items() if "unslanted" in k), default=None)
        normal_devs = by_geom.get("unslanted_normal", [])
        normal_median = _stats.median(normal_devs) if normal_devs else None
        lines.append(macro("RCWAUnslantedMaxDev", fmt(unslanted_max, ".2f")))
        lines.append(macro("RCWANormalMedianDev", fmt(normal_median, ".3f")))
    else:
        lines.append(macro("RCWAUnslantedMaxDev", None))
        lines.append(macro("RCWANormalMedianDev", None))

    return "".join(lines)


def build_validation_macros() -> str:
    """Macros for experiments/fit_literature_curves.py's output
    (results_literature_fit.json) -- Phase 6/Twin Validation. Emits one
    NRMSE/fit_quality macro per fitted source, plus a count, so Section 6
    can cite exact numbers without hand-typing them. Ground rule 4 applies
    here specifically: a poor fit gets its real NRMSE macro'd in, not
    rounded away or omitted."""
    lines = ["\n% --- validation (Phase 6 / Section 6) macros ---\n"]
    fit_data = _load("results_literature_fit.json")
    fits = fit_data.get("fits", []) if fit_data else []

    lines.append(macro("NLiteratureSources", str(len(fits))))

    for fit in fits:
        stem = fit["file"].replace(".csv", "")
        slug = "".join(ch for ch in stem.title().replace("_", "") if ch.isalpha())
        lines.append(macro(f"NRMSE{slug}", fmt(fit["nrmse"], ".2f")))

    if fits:
        worst = max(fits, key=lambda f: f["nrmse"])
        best = min(fits, key=lambda f: f["nrmse"])
        lines.append(macro("NRMSEWorstFit", fmt(worst["nrmse"], ".2f")))
        lines.append(macro("NRMSEBestFit", fmt(best["nrmse"], ".2f")))
        n_good = sum(1 for f in fits if f["fit_quality"] == "GOOD")
        lines.append(macro("NGoodFits", str(n_good)))

        in_regime = [f for f in fits if 1.96 <= f["K"] <= 15.71]
        if in_regime:
            worst_ir = max(in_regime, key=lambda f: f["nrmse"])
            best_ir = min(in_regime, key=lambda f: f["nrmse"])
            lines.append(macro("NRMSEWorstInRegime", fmt(worst_ir["nrmse"], ".2f")))
            lines.append(macro("NRMSEBestInRegime", fmt(best_ir["nrmse"], ".2f")))
            lines.append(macro("NInRegimeSources", str(len(in_regime))))
        else:
            lines.append(macro("NRMSEWorstInRegime", None))
            lines.append(macro("NRMSEBestInRegime", None))
            lines.append(macro("NInRegimeSources", "0"))

        bayfol = [f for f in fits if "bruder2017" in f.get("file", "")
                 and f.get("second_param") == "dn_max"]
        if len(bayfol) == 2:
            vals = sorted(f["second_param_fit"] for f in bayfol)
            ratio = vals[1] / vals[0] if vals[0] > 0 else None
            lines.append(macro("BayfolDnMaxRatio", fmt(ratio, ".1f") if ratio else None))
        else:
            lines.append(macro("BayfolDnMaxRatio", None))
    else:
        lines.append(macro("NRMSEWorstFit", None))
        lines.append(macro("NRMSEBestFit", None))
        lines.append(macro("NRMSEWorstInRegime", None))
        lines.append(macro("NRMSEBestInRegime", None))
        lines.append(macro("NInRegimeSources", "0"))
        lines.append(macro("BayfolDnMaxRatio", None))
        lines.append(macro("NGoodFits", None))

    return "".join(lines)


def build_shrinkage_bound_macros() -> str:
    """Macros for the Discussion's shrinkage-induced lateral-shift bound
    (D.4 in the work spec: 'named in the intro, never quantified' --
    closed by computing the exact, already-implemented shrinkage/slant
    shift formula in holomedia/diffraction.py at the default medium's
    parameters, not by asserting the effect is negligible without
    checking, and not by inventing a number)."""
    import math
    lines = ["\n% --- shrinkage-induced shift bound (Discussion) macros ---\n"]
    try:
        from holomedia import MediumParams
        p = MediumParams()
        slant_deg = 20.0
        tan_phi = math.tan(math.radians(slant_deg))
        shift_um = p.shrinkage * tan_phi * p.thickness
        shift_nm = shift_um * 1000.0
        K_LO, K_HI = 1.96, 15.71
        frac_lo = shift_um / (2 * math.pi / K_LO) * 100.0
        frac_hi = shift_um / (2 * math.pi / K_HI) * 100.0
        lines.append(macro("ShrinkagePct", fmt(p.shrinkage * 100, ".1f")))
        lines.append(macro("ShrinkageSlantDeg", fmt(slant_deg, ".0f")))
        lines.append(macro("ShrinkageThicknessUm", fmt(p.thickness, ".0f")))
        lines.append(macro("ShrinkageShiftNm", fmt(shift_nm, ".1f")))
        lines.append(macro("ShrinkageFracLowK", fmt(frac_lo, ".1f")))
        lines.append(macro("ShrinkageFracHighK", fmt(frac_hi, ".1f")))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: shrinkage-bound macros failed ({e}); "
              f"emitting PENDING.")
        for name in ("ShrinkagePct", "ShrinkageSlantDeg", "ShrinkageThicknessUm",
                    "ShrinkageShiftNm", "ShrinkageFracLowK", "ShrinkageFracHighK"):
            lines.append(macro(name, None))
    return "".join(lines)


def build_r1_macros() -> str:
    """ROneSeedValue -- pulled from the actual results file's own recorded
    seed (results_r1_reconstructions.json), not the script constant
    directly, so a future change to make_r1_reconstructions.py's SEED
    can't silently drift from what the caption claims."""
    lines = ["\n% --- R1 reconstruction figure macros ---\n"]
    d = _load("results_r1_reconstructions.json")
    if d and d.get("results"):
        seeds = {r["seed"] for r in d["results"]}
        lines.append(macro("ROneSeedValue", str(seeds.pop()) if len(seeds) == 1 else None))
    else:
        lines.append(macro("ROneSeedValue", None))
    return "".join(lines)


def build_cost_benefit_macros() -> str:
    """ComputeMatchRatio for the D.3 cost-benefit paragraph -- pulled
    directly from experiments/manifest.py's own constant, not retyped."""
    lines = ["\n% --- cost-benefit (Sec. 5.1) macros ---\n"]
    try:
        from manifest import COMPUTE_MATCH_RATIO
        lines.append(macro("ComputeMatchRatio", fmt(COMPUTE_MATCH_RATIO, ".1f")))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: cost-benefit macros failed ({e}); emitting PENDING.")
        lines.append(macro("ComputeMatchRatio", None))
    return "".join(lines)


def build_baseline_completeness_macros() -> str:
    """Macros for Sec. 5.2 (Baseline completeness, F4b): min/max paired
    gain of GS and LPC over media-blind SGD at budget=2x, and MIL's own
    min at the same budget for the contrast. Computed directly via
    analysis.aggregate (not read from a pre-baked paper_numbers.json
    field, unlike build_macros above) -- still fully regenerated from the
    raw per-job result JSONs each run, just one aggregation hop shorter;
    ground rule 1 (no hand-typed numbers in the manuscript) still holds,
    this is the "goes into a script" the rule requires."""
    lines = ["\n% --- baseline completeness (Sec. 5.2 / F4b) macros ---\n"]
    try:
        from analysis.aggregate import (load_grouped_complete, gain_curve, gain_vs_bsgd_seed_mean)
        grouped = load_grouped_complete()
        for method, macro_prefix in (("GS", "GSGain"), ("LPC", "LPCGain")):
            curve = gain_vs_bsgd_seed_mean(grouped, "M1", 2.0, method=method)
            vals = [v[1] for v in curve]
            lines.append(macro(f"{macro_prefix}Min", fmt(min(vals), ".2f") if vals else None))
            lines.append(macro(f"{macro_prefix}Max", fmt(max(vals), ".2f") if vals else None))
        mil_curve = gain_curve(grouped, "M1", 2.0, method="MIL")
        mil_vals = [v[1] for v in mil_curve]
        lines.append(macro("MILGainMinAtTwoX", fmt(min(mil_vals), ".2f") if mil_vals else None))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: baseline-completeness macros failed ({e}); "
              f"emitting PENDING for all of them.")
        for name in ("GSGainMin", "GSGainMax", "LPCGainMin", "LPCGainMax", "MILGainMinAtTwoX"):
            lines.append(macro(name, None))
    return "".join(lines)


def build_wp3_baseline_macros() -> str:
    """WP3 (Applied Optics revision) macros: paired-gain range for the two
    new baselines (RSGD, GPC) over BSGD at budget=2x, alongside SAT's, so
    the revised Sec. 5.2 text can state where the cheap surrogate and the
    two new baselines land without hand-typing. RSGD is a seeded optimizer
    (gain_curve); GPC is closed-form/seed=0-only like GS/LPC
    (gain_vs_bsgd_seed_mean) -- same split make_fig1_paired_gain uses,
    for the same reason (see figures/make_all.py)."""
    lines = ["\n% --- WP3 baseline (RSGD/GPC, Sec. 5.2) macros ---\n"]
    try:
        from analysis.aggregate import (load_grouped_complete, gain_curve, gain_vs_bsgd_seed_mean)
        grouped = load_grouped_complete()
        rsgd_curve = gain_curve(grouped, "M1", 2.0, method="RSGD")
        rsgd_vals = [v[1] for v in rsgd_curve]
        lines.append(macro("RSGDGainMin", fmt(min(rsgd_vals), ".2f") if rsgd_vals else None))
        lines.append(macro("RSGDGainMax", fmt(max(rsgd_vals), ".2f") if rsgd_vals else None))
        gpc_curve = gain_vs_bsgd_seed_mean(grouped, "M1", 2.0, method="GPC")
        gpc_vals = [v[1] for v in gpc_curve]
        lines.append(macro("GPCGainMin", fmt(min(gpc_vals), ".2f") if gpc_vals else None))
        lines.append(macro("GPCGainMax", fmt(max(gpc_vals), ".2f") if gpc_vals else None))
        lpc_curve = gain_vs_bsgd_seed_mean(grouped, "M1", 2.0, method="LPC")
        lpc_by_K = {k: v for k, v, *_ in lpc_curve}
        gpc_by_K = {k: v for k, v, *_ in gpc_curve}
        common_Ks = sorted(set(lpc_by_K) & set(gpc_by_K))
        diffs = [abs(gpc_by_K[k] - lpc_by_K[k]) for k in common_Ks]
        lines.append(macro("GPCLPCMaxAbsDiffTwoX", fmt(max(diffs), ".2f") if diffs else None))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: WP3 baseline macros failed ({e}); "
              f"emitting PENDING for all of them.")
        for name in ("RSGDGainMin", "RSGDGainMax", "GPCGainMin", "GPCGainMax",
                     "GPCLPCMaxAbsDiffTwoX"):
            lines.append(macro(name, None))
    return "".join(lines)


def build_wp4_macros() -> str:
    """WP4 (Applied Optics revision, statistics redesign) macros: target-
    ensemble gain per target kind (S4) and noise-robustness gain (S5),
    both at the fixed near-cliff K/budget point those tiers use. Also
    emits bootstrap CI bounds alongside the t-distribution ones already
    used elsewhere, per WP4's item 2."""
    lines = ["\n% --- WP4 (target ensemble / noise robustness, Sec. 5.x) macros ---\n"]
    try:
        from analysis.aggregate import (load_grouped_complete, s4_target_ensemble_summary,
                                        s5_noise_robustness_summary)
        grouped = load_grouped_complete()
        s4 = s4_target_ensemble_summary(grouped)
        if s4["status"] == "ok":
            for kind, label in (("bars", "Bars"), ("spots", "Spots"),
                               ("random_binary", "RandomBinary")):
                for budget, blabel in ((2.0, "TwoX"), (8.0, "EightX")):
                    stat = s4["by_kind"].get(kind, {}).get(budget, {})
                    lines.append(macro(f"SFourGain{label}{blabel}",
                                       fmt(stat.get("mean"), ".2f")))
                    lines.append(macro(f"SFourBootCILo{label}{blabel}",
                                       fmt(stat.get("boot_ci_lo"), ".2f")))
                    lines.append(macro(f"SFourBootCIHi{label}{blabel}",
                                       fmt(stat.get("boot_ci_hi"), ".2f")))
        else:
            for kind_label in ("Bars", "Spots", "RandomBinary"):
                for blabel in ("TwoX", "EightX"):
                    for prefix in ("SFourGain", "SFourBootCILo", "SFourBootCIHi"):
                        lines.append(macro(f"{prefix}{kind_label}{blabel}", None))

        s5 = s5_noise_robustness_summary(grouped)
        if s5["status"] == "ok":
            lines.append(macro("SFiveNoiseStdPct", fmt(s5["noise_std"] * 100, ".0f")))
            lines.append(macro("SFiveNoiselessGain", fmt(s5["noiseless"].get("mean"), ".2f")))
            lines.append(macro("SFiveNoisyGain", fmt(s5["noisy"].get("mean"), ".2f")))
        else:
            for name in ("SFiveNoiseStdPct", "SFiveNoiselessGain", "SFiveNoisyGain"):
                lines.append(macro(name, None))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: WP4 macros failed ({e}); emitting PENDING.")
        for kind_label in ("Bars", "Spots", "RandomBinary"):
            for blabel in ("TwoX", "EightX"):
                for prefix in ("SFourGain", "SFourBootCILo", "SFourBootCIHi"):
                    lines.append(macro(f"{prefix}{kind_label}{blabel}", None))
        for name in ("SFiveNoiseStdPct", "SFiveNoiselessGain", "SFiveNoisyGain"):
            lines.append(macro(name, None))
    return "".join(lines)


def build_wp5_macros() -> str:
    """WP5 (Applied Optics revision, joint miscalibration Monte Carlo)
    macros: S6's paired-gain distribution across joint (all-four-
    parameter) perturbation draws."""
    lines = ["\n% --- WP5 (joint miscalibration Monte Carlo, Sec. 5.x) macros ---\n"]
    try:
        from analysis.aggregate import load_grouped_complete, s6_joint_mismatch_summary
        grouped = load_grouped_complete()
        s6 = s6_joint_mismatch_summary(grouped)
        if s6["status"] == "ok":
            lines.append(macro("SSixNDraws", str(s6["n_draws"])))
            lines.append(macro("SSixMeanGain", fmt(s6["stats"]["mean"], ".2f")))
            lines.append(macro("SSixBootCILo", fmt(s6["stats"]["boot_ci_lo"], ".2f")))
            lines.append(macro("SSixBootCIHi", fmt(s6["stats"]["boot_ci_hi"], ".2f")))
            lines.append(macro("SSixNNegative", str(s6["n_negative"])))
            lines.append(macro("SSixWorstDrawGain", fmt(s6["worst_draw_gain"], ".2f")))
            lines.append(macro("SSixBestDrawGain", fmt(s6["best_draw_gain"], ".2f")))
            from manifest import S6_PCT_RANGE
            lines.append(macro("SSixPctRange", fmt(S6_PCT_RANGE, ".0f")))
        else:
            for name in ("SSixNDraws", "SSixMeanGain", "SSixBootCILo", "SSixBootCIHi",
                        "SSixNNegative", "SSixWorstDrawGain", "SSixBestDrawGain", "SSixPctRange"):
                lines.append(macro(name, None))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: WP5 macros failed ({e}); emitting PENDING.")
        for name in ("SSixNDraws", "SSixMeanGain", "SSixBootCILo", "SSixBootCIHi",
                    "SSixNNegative", "SSixWorstDrawGain", "SSixBestDrawGain", "SSixPctRange"):
            lines.append(macro(name, None))
    return "".join(lines)


def build_wp6_macros() -> str:
    """WP6 (Applied Optics revision, depth-resolved absorption) macros:
    S7's paired gain at each tested optical density. Macro names use
    spelled-out ODZero/ODOneTenth/ODThreeTenths (NOT literal decimal
    points or the digits from "0.1"/"0.3") -- LaTeX control words are
    letters-only, the same constraint that broke the S4/S5/S6 macro
    names earlier this revision before they were caught and fixed."""
    lines = ["\n% --- WP6 (depth-resolved absorption, Sec. 5.x) macros ---\n"]
    od_labels = [(0.0, "ODZero"), (0.1, "ODOneTenth"), (0.3, "ODThreeTenths")]
    try:
        from analysis.aggregate import load_grouped_complete, s7_depth_absorption_summary
        grouped = load_grouped_complete()
        s7 = s7_depth_absorption_summary(grouped)
        if s7["status"] == "ok":
            for od, label in od_labels:
                stat = s7["by_od"].get(od, {})
                lines.append(macro(f"SSevenGain{label}", fmt(stat.get("mean"), ".2f")))
        else:
            for _, label in od_labels:
                lines.append(macro(f"SSevenGain{label}", None))
    except Exception as e:
        print(f"[make_numbers_tex] WARNING: WP6 macros failed ({e}); emitting PENDING.")
        for _, label in od_labels:
            lines.append(macro(f"SSevenGain{label}", None))
    return "".join(lines)


_KLAB3 = {1.309: "Sub", 3.927: "Near", 5.236: "Post"}
_S1X_LAB = {"baseline": "Baseline", "no_monomer_depletion": "NoMonomer",
            "no_dye_depletion": "NoDye", "no_saturation": "NoSat",
            "only_tanh": "OnlyTanh", "only_dye": "OnlyDye",
            "only_monomer": "OnlyMonomer", "linear_recording": "Linear",
            "linear_slope_matched": "LinearMatched",
            "no_monomer_depletion_matched": "NoMonomerMatched",
            "only_dye_matched": "OnlyDyeMatched",
            "only_tanh_matched": "OnlyTanhMatched"}
_S1_LAB = {"baseline": "Baseline", "no_saturation": "NoSat", "no_diffusion": "NoDiff",
           "no_nonlocality": "NoNonloc", "no_dye_depletion": "NoDye"}


def _klab(K):
    for k, lab in _KLAB3.items():
        if abs(float(K) - k) < 2e-3:
            return lab
    return None


def build_path7_macros(pn: dict) -> str:
    """Macros for the complete-cell main grid, ablations and twin fits: grid-cell counts on
    complete M1 cells only, K-resolved S1, the S1X mechanism factorial, SAT
    per K, reduced M2, S3 dn_max points and the held-out twin fit."""
    L = ["\n% --- main grid (complete M1 cells only), ablations, twin fits ---\n"]
    closure = [r for r in pn.get("m1_headroom_closure", []) if r.get("gain_curve")]
    cells = [(r["budget"], K, g, lo, hi) for r in closure for K, g, lo, hi in r["gain_curve"]]
    Ks = sorted({c[1] for c in cells})
    L.append(macro("MOneNK", str(len(Ks)) if Ks else None))
    L.append(macro("MOneNCells", str(len(cells)) if cells else None))
    L.append(macro("MOneKMin", fmt(Ks[0]) if Ks else None))
    L.append(macro("MOneKMax", fmt(Ks[-1]) if Ks else None))
    L.append(macro("MOneKList", ", ".join(f"{k:.2f}" for k in Ks) if Ks else None))
    L.append(macro("MOneNPositive", str(sum(1 for c in cells if c[2] > 0)) if cells else None))
    L.append(macro("MOneNCIAboveZero",
                   str(sum(1 for c in cells if c[3] is not None and c[3] > 0)) if cells else None))
    L.append(macro("MOneNCIIncludesZero",
                   str(sum(1 for c in cells if c[3] is not None and c[3] <= 0 <= c[4])) if cells else None))
    neg = [c for c in cells if c[2] <= 0]
    L.append(macro("MOneNNegative", str(len(neg)) if cells else None))
    if neg:
        b, K, g, lo, hi = min(neg, key=lambda c: c[2])
        L += [macro("MOneNegK", fmt(K)), macro("MOneNegBudget", f"{b:.0f}"),
              macro("MOneNegGain", fmt(g)), macro("MOneNegCILo", fmt(lo)),
              macro("MOneNegCIHi", fmt(hi, ".3f"))]
    else:
        L += [macro(n, None) for n in ("MOneNegK", "MOneNegBudget", "MOneNegGain",
                                       "MOneNegCILo", "MOneNegCIHi")]
    for r in closure:
        lab = BUDGET_LABELS[r["budget"]]
        best = max(r["gain_curve"], key=lambda c: c[1])
        top = max(r["gain_curve"], key=lambda c: c[0])
        L += [macro(f"MaxGain{lab}", fmt(best[1])), macro(f"MaxGainK{lab}", fmt(best[0])),
              macro(f"GainHighK{lab}", fmt(top[1])),
              macro(f"GainHighKLo{lab}", fmt(top[2], ".3f")),
              macro(f"GainHighKHi{lab}", fmt(top[3], ".3f"))]
    L.append(macro("MOneNExcluded", str(len(pn.get("m1_incomplete_cells_excluded", [])))))

    s1 = pn.get("s1_by_K", {})
    for cond, clab in _S1_LAB.items():
        byK = s1.get("by_condition", {}).get(cond, {}) if s1.get("status") == "ok" else {}
        for K, klab in _KLAB3.items():
            st = next((v for k, v in byK.items() if _klab(k) == klab), {})
            L.append(macro(f"SOneG{clab}{klab}", fmt(st.get("mean"))))
    for K, klab in _KLAB3.items():
        L.append(macro(f"SOneK{klab}", fmt(K)))

    sx = pn.get("s1x_by_K", {})
    for cond, clab in _S1X_LAB.items():
        byK = sx.get("by_condition", {}).get(cond, {}) if sx.get("status") == "ok" else {}
        for K, klab in _KLAB3.items():
            st = next((v for k, v in byK.items() if _klab(k) == klab), {})
            L.append(macro(f"SXG{clab}{klab}", fmt(st.get("mean"))))
            L.append(macro(f"SXN{clab}{klab}", str(st["n"]) if st.get("n") else None))
    diffs = []
    b1 = s1.get("by_condition", {}).get("baseline", {}) if s1.get("status") == "ok" else {}
    bx = sx.get("by_condition", {}).get("baseline", {}) if sx.get("status") == "ok" else {}
    for k, v in bx.items():
        if k in b1:
            diffs.append(abs(v["mean"] - b1[k]["mean"]))
    L.append(macro("SXDeviceMaxDiff", fmt(max(diffs), ".3f") if diffs else None))

    sat = pn.get("sat_surrogate_summary", {})
    fr = {b: v.get("fraction_by_K", {}) for b, v in sat.get("by_budget", {}).items()
          if v.get("status") == "ok"}
    allf = [(b, float(K), f) for b, d in fr.items() for K, f in d.items()]
    low = [f for b, K, f in allf if K < 2.0]
    second = [f for b, K, f in allf if 2.5 < K < 2.7]
    if low and second:
        L += [macro("SATFracLowKMin", fmt(100 * min(low), ".0f")),
              macro("SATFracLowKMax", fmt(100 * max(low), ".0f")),
              macro("SATFracSecondKMin", fmt(100 * min(second), ".0f")),
              macro("SATFracSecondKMax", fmt(100 * max(second), ".0f")),
              macro("SATNBelowBSGD", str(sum(1 for *_, f in allf if f < 0))),
              macro("SATNCells", str(len(allf)))]
    else:
        L += [macro(n, None) for n in ("SATFracLowKMin", "SATFracLowKMax", "SATFracSecondKMin",
                                       "SATFracSecondKMax", "SATNBelowBSGD", "SATNCells")]

    dn = pn.get("s3_mismatch_summary", {}).get("by_param", {}).get("dn_max", {}).get("by_pct", {})
    for pct, lab in (("-50", "MinusFifty"), ("50", "PlusFifty")):
        L.append(macro(f"SThreeDnMaxAt{lab}", fmt(dn.get(pct, {}).get("mean"))))

    m2 = next((r for r in pn.get("m2_headroom_closure", []) if r.get("budget") == 2.0), {})
    curve = m2.get("gain_curve") or []
    for K, klab in _KLAB3.items():
        c = next((c for c in curve if _klab(c[0]) == klab), None)
        L.append(macro(f"MTwoRGain{klab}", fmt(c[1]) if c else None))
        L.append(macro(f"MTwoRLo{klab}", fmt(c[2]) if c else None))
        L.append(macro(f"MTwoRHi{klab}", fmt(c[3]) if c else None))
    sat_m2 = pn.get("sat_surrogate_summary_m2", {}).get("by_budget", {}).get("2.0", {})
    for K, klab in _KLAB3.items():
        f = next((v for k, v in sat_m2.get("fraction_by_K", {}).items() if _klab(k) == klab), None)
        L.append(macro(f"MTwoRSATFrac{klab}", fmt(100 * f, ".0f") if f is not None else None))

    ho = _load("results_twin_holdout.json")
    for var, vlab in (("A_kbleach_fixed", "A"), ("B_kbleach_free", "B")):
        for train, tlab in (("sim", "Sim"), ("exp", "Exp")):
            f = (ho or {}).get("fits", {}).get(f"{var}/{train}")
            L.append(macro(f"Holdout{vlab}{tlab}In", fmt(f["nrmse"]) if f else None))
            L.append(macro(f"Holdout{vlab}{tlab}Out", fmt(f["heldout_nrmse"]) if f else None))
            kb = f["params"].get("k_bleach") if f else None
            if f and kb is None:
                kb = ho["base_params"]["k_bleach"]
            L.append(macro(f"Holdout{vlab}{tlab}Kbleach", fmt(kb, ".3g") if kb is not None else None))
            dm = f["params"].get("dn_max") if f else None
            L.append(macro(f"Holdout{vlab}{tlab}DnMax", fmt(dm, ".3g") if dm is not None else None))
            L.append(macro(f"Holdout{vlab}{tlab}AtBound",
                           (", ".join(f["at_bound"]).replace("_", "\\_") or "none") if f else None))
    return "".join(L)


def main():
    paper_numbers = {}
    if os.path.exists(PAPER_NUMBERS_PATH):
        with open(PAPER_NUMBERS_PATH) as f:
            paper_numbers = json.load(f)
    else:
        print(f"[make_numbers_tex] WARNING: {PAPER_NUMBERS_PATH} not found "
              f"-- run analysis/aggregate.py first. Emitting all-PENDING macros.")

    tex = (build_macros(paper_numbers) + build_supplement_macros()
          + build_validation_macros() + build_baseline_completeness_macros()
          + build_shrinkage_bound_macros() + build_cost_benefit_macros()
          + build_r1_macros() + build_wp3_baseline_macros() + build_wp4_macros()
          + build_wp5_macros() + build_wp6_macros()
          + build_path7_macros(paper_numbers))
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(tex)
    n_pending = tex.count(PENDING)
    print(f"wrote {OUT_PATH} ({tex.count(chr(10)) } lines, {n_pending} macros still PENDING)")


if __name__ == "__main__":
    main()
