"""
Neural surrogate for the NPDD recording twin.

A small 1D CNN trained offline to map exposure E(x) -> recorded dn(x),
fit on random exposures from the true NPDDRecorder. Used as a cheap
(but approximate) gradient source in the gradient-pathway ablation
(experiments/ablation_gradients.py): forward/backward through the surrogate
costs one CNN pass instead of an n_steps IMEX unroll.
"""
from __future__ import annotations
import torch
import torch.nn as nn


class DnSurrogate(nn.Module):
    """1D CNN, exposure -> dn profile. Periodic (circular) padding matches
    the recorder's FFT-based periodic boundary conditions."""

    def __init__(self, n_x: int, hidden: int = 32, depth: int = 4, dtype=torch.float64):
        super().__init__()
        layers = []
        c_in = 1
        for i in range(depth):
            c_out = hidden if i < depth - 1 else 1
            layers.append(nn.Conv1d(c_in, c_out, kernel_size=9, padding=4,
                                    padding_mode="circular", dtype=dtype))
            if i < depth - 1:
                layers.append(nn.GELU())
            c_in = c_out
        self.net = nn.Sequential(*layers)
        self.n_x = n_x

    def forward(self, exposure: torch.Tensor) -> torch.Tensor:
        x = exposure.to(next(self.parameters()).dtype).view(1, 1, -1)
        return self.net(x).view(-1)


def train_surrogate(recorder, n_x: int, n_samples: int = 400, epochs: int = 200,
                    lr: float = 3e-3, seed: int = 0, verbose: bool = False):
    """Fit a DnSurrogate to `recorder` on random smooth-ish nonnegative exposures.

    Training data is generated by the true (expensive) twin; this cost is
    paid once, offline, and amortized over many downstream optimization runs
    -- the point of a surrogate gradient.
    """
    torch.manual_seed(seed)
    dtype = recorder.dtype
    surrogate = DnSurrogate(n_x, dtype=dtype)

    # random band-limited nonnegative exposures, similar statistics to what
    # the optimizer actually explores (softplus of smoothed noise)
    def sample_exposure():
        raw = torch.randn(n_x, dtype=dtype)
        f = torch.fft.fft(raw)
        freqs = torch.fft.fftfreq(n_x)
        cutoff = 0.05 + 0.4 * torch.rand(1).item()
        f = f * torch.exp(-(freqs / cutoff) ** 2)
        smooth = torch.fft.ifft(f).real
        return torch.nn.functional.softplus(2.0 * smooth) + 1e-3

    with torch.no_grad():
        Es = torch.stack([sample_exposure() for _ in range(n_samples)])
        dns = torch.stack([recorder(Es[i]) for i in range(n_samples)])

    opt = torch.optim.Adam(surrogate.parameters(), lr=lr)
    for ep in range(epochs):
        opt.zero_grad()
        pred = surrogate.net(Es.unsqueeze(1)).squeeze(1)
        loss = torch.mean((pred - dns) ** 2)
        loss.backward()
        opt.step()
        if verbose and ep % 50 == 0:
            print(f"  [surrogate] epoch {ep:4d}  mse {float(loss):.3e}")
    return surrogate, float(loss.detach())
