r"""
Phase 7.1: check_consistency.py -- fails the build if oe_main.tex has any
hard-coded digit adjacent to "seed", "dB", or "rad/" outside a macro
invocation. This is the guard against exactly the bug the master prompt
names: an old draft's abstract claiming "2 seeds" while its own results
section retracts it. Every such quantity must come from a \NumbersTexMacro
(numbers.tex, generated by make_numbers_tex.py from real aggregated data),
never typed directly into the manuscript body.

Method: strip LaTeX comments and macro invocations (\Foo or \Foo{...} --
these are fine, they're exactly how numbers should appear) from the text,
then regex-search what's left for a hard-coded number next to one of the
three trigger words. This intentionally does NOT touch numbers.tex itself
(that file's whole job is to contain literal numbers).

Usage: python scripts/check_consistency.py [path/to/oe_main.tex]
Exit code 0 = clean, 1 = violations found (build should fail).
"""
import os
import re
import sys

TRIGGER_WORDS = ["seed", "seeds", "dB", "rad/"]

# \command or \command{...} (non-greedy, single level of braces -- adequate
# for the simple \MacroName or \MacroName{arg} invocations this checks for;
# nested-brace macro args are rare enough in practice that a stricter
# balanced-brace parser isn't worth the complexity here)
MACRO_INVOCATION_RE = re.compile(r"\\[A-Za-z]+(\{[^{}]*\})?")
COMMENT_RE = re.compile(r"(?<!\\)%.*$", re.MULTILINE)

# number adjacent (within a few non-word chars) to a trigger word, either order
NUMBER_NEAR_TRIGGER_RE = re.compile(
    r"(\d+(?:\.\d+)?)\s{0,3}(" + "|".join(re.escape(w) for w in TRIGGER_WORDS) + r")"
    r"|(" + "|".join(re.escape(w) for w in TRIGGER_WORDS) + r")\s{0,3}[-=:]?\s{0,3}(\d+(?:\.\d+)?)",
    re.IGNORECASE,
)


def strip_comments_and_macros(text: str) -> str:
    text = COMMENT_RE.sub("", text)
    text = MACRO_INVOCATION_RE.sub(" ", text)
    return text


def find_violations(text: str) -> list[tuple]:
    """Returns [(line_no, matched_text), ...] for every hard-coded-number-
    near-trigger-word match found OUTSIDE macro invocations."""
    stripped = strip_comments_and_macros(text)
    violations = []
    for i, line in enumerate(stripped.splitlines(), start=1):
        for m in NUMBER_NEAR_TRIGGER_RE.finditer(line):
            violations.append((i, m.group(0).strip()))
    return violations


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(__file__), "..", "..", "paper", "oe_main.tex")
    if not os.path.exists(path):
        print(f"[check_consistency] {path} does not exist yet -- nothing to check "
              f"(this is expected before Phase 7.2 writes the manuscript).")
        return 0

    with open(path, encoding="utf-8") as f:
        text = f.read()
    violations = find_violations(text)

    if violations:
        print(f"[check_consistency] FAILED: {len(violations)} hard-coded number(s) "
              f"adjacent to seed/dB/rad\\/ found outside macro invocations in {path}:")
        for line_no, snippet in violations:
            print(f"  line {line_no}: {snippet!r}")
        print("Every such quantity must come from a numbers.tex macro "
              "(scripts/make_numbers_tex.py), not be typed directly.")
        return 1

    print(f"[check_consistency] OK: no hard-coded seed/dB/rad\\/ numbers found in {path}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
