r"""
Phase 7.1: generate paper/numbers.tex -- LaTeX macros from
results/summary/paper_numbers.json (analysis/aggregate.py's output). The
manuscript (paper/oe_main.tex) uses ONLY these macros for any quantitative
claim; this is the structural fix for transcription errors (the K=7.85dB
oracle-vs-K=7.85rad/um coincidence resolved in docs/provenance_report.md)
and for internal contradictions (an old draft's abstract claiming "2
seeds" while its own Sec. 5 retracts it -- with a \SeedCount macro
sourced from one place, that class of bug becomes unbuildable).

Every macro is emitted, even when the underlying data doesn't exist yet:
missing data emits \newcommand{\Foo}{[PENDING]} (visibly flagged in the
compiled PDF, red-colored if xcolor is loaded) rather than being silently
omitted (which would just produce an "undefined control sequence" LaTeX
error with no indication of WHY) or fabricated (ground rule 1). This
means oe_main.tex can be built at any point in the project and will
render, honestly showing exactly what's pending.

Usage: python scripts/make_numbers_tex.py
"""
import json
import os
import statistics
import sys

HERE = os.path.dirname(__file__)
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, ROOT)

PAPER_NUMBERS_PATH = os.path.join(ROOT, "results", "summary", "paper_numbers.json")
OUT_PATH = os.path.join(ROOT, "..", "paper", "numbers.tex")

BUDGET_LABELS = {2.0: "TwoX", 4.0: "FourX", 8.0: "EightX"}
PENDING = r"\textcolor{red}{[PENDING]}"


def fmt(value, spec=".2f"):
    if value is None:
        return None
    return format(value, spec)


def macro(name: str, value) -> str:
    body = PENDING if value is None else value
    return f"\\newcommand{{\\{name}}}{{{body}}}\n"


def build_macros(paper_numbers: dict) -> str:
    lines = ["% AUTO-GENERATED by scripts/make_numbers_tex.py -- DO NOT HAND-EDIT.\n",
            "% Regenerate: python scripts/make_numbers_tex.py\n",
            "\\usepackage{xcolor}  % for the [PENDING] flag color, harmless if already loaded\n",
            "\n"]

    closure = paper_numbers.get("e1_headroom_closure", [])
    seed_counts = set()
    for row in closure:
        label = BUDGET_LABELS.get(row.get("budget"))
        if label is None:
            continue
        if row.get("status") == "no_data":
            lines.append(macro(f"MeasuredContrast{label}", None))
            lines.append(macro(f"KcPred{label}", None))
            lines.append(macro(f"Kstar{label}Interp", None))
            lines.append(macro(f"Kstar{label}CI", None))
            lines.append(macro(f"MeanGain{label}", None))
            continue
        lines.append(macro(f"MeasuredContrast{label}", fmt(row.get("measured_contrast_C"))))
        lines.append(macro(f"KcPred{label}", fmt(row.get("predicted_Kc_from_measured_C"))))
        lines.append(macro(f"Kstar{label}Interp", fmt(row.get("observed_Kstar_interp"))))
        lines.append(macro(f"Kstar{label}CI", fmt(row.get("observed_Kstar_ci"))))
        curve = row.get("gain_curve", [])
        mean_gain = statistics.fmean(g for _, g, _, _ in curve) if curve else None
        lines.append(macro(f"MeanGain{label}", fmt(mean_gain)))

    # seed count: consistent across all logged E1 rows, or PENDING if absent/inconsistent
    per_config = paper_numbers.get("per_config", {})
    e1_seed_counts = {v["n_seeds"] for k, methods in per_config.items()
                      if k.startswith("E1/") for v in methods.values()}
    if len(e1_seed_counts) == 1:
        lines.append(macro("SeedCount", str(next(iter(e1_seed_counts)))))
    else:
        lines.append(macro("SeedCount", None))

    lines.append(macro("NResultFiles", str(paper_numbers.get("n_result_files", 0))))
    return "".join(lines)


def _load(*parts):
    path = os.path.join(ROOT, *parts)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def build_supplement_macros() -> str:
    """Macros for already-real supplementary data (gradient ablation, RCWA
    incl. E7, GPU mesh convergence, GPU wavelength detuning) -- routed
    through numbers.tex too, for the same zero-hand-typed-numbers reason
    Sec. 7.1 applies to the main manuscript, even though this data
    predates Phase 3 and isn't gated on it."""
    lines = ["\n% --- supplement macros (already-real data, not Phase-3-gated) ---\n"]

    ablation = _load("results_ablation_gradients.json")
    lines.append(macro("AblationCheckpointCosSim",
                       fmt(ablation["fidelity"]["checkpoint_cossim"], ".3f") if ablation else None))
    lines.append(macro("AblationSurrogateCosSim",
                       fmt(ablation["fidelity"]["surrogate_cossim"], ".3f") if ablation else None))

    rcwa3 = _load("results_rcwa.json")
    lines.append(macro("RCWAMaxDevThreeCase",
                       fmt(rcwa3.get("max_abs_deviation"), ".3f") if rcwa3 else None))
    rcwa_e7 = _load("results_rcwa_e7.json")
    lines.append(macro("RCWAE7MaxDev",
                       fmt(rcwa_e7.get("max_abs_deviation"), ".3f") if rcwa_e7 else None))
    lines.append(macro("RCWAE7NCases", str(rcwa_e7["n_cases"]) if rcwa_e7 else None))

    mesh = _load("results", "gpu_reruns", "npdd_mesh_sweep", "results.json")
    if mesh:
        psnrs = [row["psnr"] for row in mesh["mesh_density"].values()]
        lines.append(macro("MeshPSNRSpread", fmt(max(psnrs) - min(psnrs), ".3f")))
    else:
        lines.append(macro("MeshPSNRSpread", None))

    wl = _load("results", "gpu_reruns", "bpm_wavelength_sweep", "results.json")
    lines.append(macro("WavelengthDesignPSNR",
                       fmt(wl["recording"]["psnr_at_design_wavelength"], ".2f") if wl else None))

    return "".join(lines)


def main():
    paper_numbers = {}
    if os.path.exists(PAPER_NUMBERS_PATH):
        with open(PAPER_NUMBERS_PATH) as f:
            paper_numbers = json.load(f)
    else:
        print(f"[make_numbers_tex] WARNING: {PAPER_NUMBERS_PATH} not found "
              f"-- run analysis/aggregate.py first. Emitting all-PENDING macros.")

    tex = build_macros(paper_numbers) + build_supplement_macros()
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(tex)
    n_pending = tex.count(PENDING)
    print(f"wrote {OUT_PATH} ({tex.count(chr(10)) } lines, {n_pending} macros still PENDING)")


if __name__ == "__main__":
    main()
